const ActionTypes = {
  UPDATE_MECHANIC: "UPDATE_MECHANIC",
  UPDATE_SERVICES: "UPDATE_SERVICES",
  UPDATE_CURRENT_SESSION: "UPDATE_CURRENT_SESSION",
  UPDATE_CURRENT_CUSTOMER: "UPDATE_CURRENT_CUSTOMER",
  UPDATE_IS_ONLINE: "UPDATE_IS_ONLINE",
  UPDATE_CUSTOMERS: "UPDATE_CUSTOMERS",
  UPDATE_SESSIONS: "UPDATE_SESSIONS",
  UPDATE_REVIEWS: "UPDATE_REVIEWS",
};

export default ActionTypes;
